apiVersion: apps/v1
kind: Deployment
metadata:
  name: devonn-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devonn-backend
  template:
    metadata:
      labels:
        app: devonn-backend
    spec:
      containers:
      - name: devonn-backend
        image: "${BACKEND_IMAGE}"
        ports:
        - containerPort: 8080
