apiVersion: apps/v1
kind: Deployment
metadata:
  name: devonn-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devonn-frontend
  template:
    metadata:
      labels:
        app: devonn-frontend
    spec:
      containers:
      - name: devonn-frontend
        image: "${FRONTEND_IMAGE}"
        ports:
        - containerPort: 80
